# Use the lightweight Nginx Alpine image
FROM nginx:alpine

# Copy your custom HTML file to the default Nginx public folder
COPY index.html /usr/share/nginx/html/index.html

# Nginx runs on port 80 by default
EXPOSE 80